# frozen_string_literal: true

require "rails/generators"
require "yaml"

module Poetry
  # `rails g poetry:block <name>` - copies a vetted composed
  # screen into the app as source the app OWNS. Blocks are starting points
  # an agent (or a person) edits, not components it configures: the file
  # lands under app/views/blocks/ as a partial, the sample content is meant
  # to be replaced in place, and `poetry check` keeps validating the result
  # like any other template. `--list` (or no argument) prints the catalog
  # from the registry's blocks section.
  class BlockGenerator < Rails::Generators::Base
    source_root File.expand_path("templates", __dir__)

    argument :block_name, type: :string, required: false,
                          banner: "block-name", desc: "the block to copy in (see --list)"
    class_option :list, type: :boolean, default: false, desc: "list the available blocks"

    desc "Copy a vetted poetry block (a composed screen) into app/views/blocks/ as app-owned source"

    OWNERSHIP_HEADER = "<%%# generated by `bin/rails g poetry:block %<name>s` - this file is yours: " \
                       "rename, move, and edit freely (sample content is meant to be replaced). " \
                       "Catalog: /poetry/llms.txt; verify edits with poetry check. %%>"

    def copy_block
      return print_catalog if options[:list] || block_name.nil?

      name = block_name.tr("_", "-")
      entry = catalog[name]
      unless entry
        say_status :error, "unknown block #{name.inspect}", :red
        print_catalog
        raise Thor::Error, "unknown block #{name.inspect}"
      end

      source = Poetry::Ui.root.join(entry.fetch("template")).read
      body = source.sub(/\A<%#\s*poetry:block[^%]*%>\n?/, "")
      header = format(OWNERSHIP_HEADER, name: name)
      create_file "app/views/blocks/_#{name.tr("-", "_")}.html.erb", "#{header}\n#{body}"
      say_status :render, "<%= render \"blocks/#{name.tr("-", "_")}\" %>", :blue
    end

    private

    def catalog
      @catalog ||= YAML.safe_load_file(
        Poetry::Ui.root.join(Poetry::Core::Registry::RELATIVE_PATH)
      )["blocks"] || {}
    end

    def print_catalog
      say "poetry blocks (bin/rails g poetry:block <name>):"
      catalog.each do |name, entry|
        say "  #{name.ljust(18)} #{entry["title"]} - #{entry["description"]}"
      end
    end
  end
end
