# frozen_string_literal: true

# generated by `bin/rails g poetry:pagination will_paginate` - this file is
# yours: edit freely. Usage (the renderer: option per call - will_paginate
# deprecates the global default):
#
#   <%= will_paginate @records, renderer: PoetryLinkRenderer %>
#
# to_html is replaced wholesale (the upstream comment invites it); the
# inherited url(page) keeps will_paginate's GET-param merging and nested
# param_name support. Doctrine: poetry owns the window - inner_window/
# outer_window do not apply; will_paginate's container options are
# absorbed by poetry's own <nav> landmark. Upstream behavior kept: the
# helper returns nil when total_pages <= 1 (this class is never called).
#
# Note: will_paginate itself is in maintenance mode (no new features or
# releases since mid-2024). This adapter supports apps that already use
# it; for a new project, prefer kaminari or pagy.
class PoetryLinkRenderer < WillPaginate::ActionView::LinkRenderer
  def to_html
    @template.poetry_pagination(
      current: @collection.current_page.to_i,
      total: @collection.total_pages,
      path: ->(page) { url(page) },
      **(@options[:poetry] || {})
    )
  end
end
