# frozen_string_literal: true

# generated by `bin/rails g poetry:pagination pagy` - this file is yours:
# edit freely. Usage, anywhere a view holds a @pagy:
#
#   <%= poetry_pagy_nav(@pagy) %>
#
# Doctrine: poetry owns the window (siblings:/edges: options here) -
# pagy's slots: does not apply. Mirrors the other paginators' behavior of
# rendering nothing at a single page. Needs pagy >= 43 (the leap-version
# redesign: instance-method navs, page_url); pagy's *_js navs are
# deliberately not adapted - their token protocol couples to pagy.js.
module PoetryPagyHelper
  def poetry_pagy_nav(pagy, **options)
    unless Pagy::VERSION.to_i >= 43
      raise "poetry_pagy_nav needs pagy >= 43 (found #{Pagy::VERSION}) - " \
            "the pre-43 extras API is a different world"
    end
    return "".html_safe if pagy.last <= 1

    poetry_pagination(
      current: pagy.page.to_i,
      total: pagy.last,
      path: ->(page) { pagy.page_url(page) },
      **options
    )
  end
end
