# frozen_string_literal: true

require "rails/generators"

module Poetry
  # `rails g poetry:agent_rules` - the two-file, opposite-lifecycle agent
  # ruleset:
  #
  #   .poetry/agent-rules.md  gem-owned, FORCE-overwritten every run
  #                           (generated live from the component registry)
  #   .poetry/house-rules.md  seeded once, then user-owned - never touched again
  #
  # plus an idempotent marker-import into CLAUDE.md and AGENTS.md:
  # insert-between-markers, replace-on-rerun, and detect-but-never-rewrite
  # when a file carries a broken half-marker.
  class AgentRulesGenerator < Rails::Generators::Base
    START_MARKER = "<!-- poetry:agent-rules:start -->"
    END_MARKER = "<!-- poetry:agent-rules:end -->"

    IMPORT_BLOCK = <<~MD.freeze
      #{START_MARKER}
      Follow the poetry component rules in `.poetry/agent-rules.md` (generated - do not edit)
      and the project overrides in `.poetry/house-rules.md`.
      #{END_MARKER}
    MD

    HOUSE_RULES_SEED = <<~MD
      # poetry house rules

      Project-specific overrides and additions to the generated poetry agent
      rules. This file is yours - poetry seeds it once and never touches it
      again.
    MD

    desc "Install the poetry agent ruleset (.poetry/agent-rules.md + house-rules.md + CLAUDE.md/AGENTS.md import)"

    def create_agent_rules
      create_file ".poetry/agent-rules.md", generated_rules, force: true
    end

    def seed_house_rules
      return if File.exist?(File.join(destination_root, ".poetry/house-rules.md"))

      create_file ".poetry/house-rules.md", HOUSE_RULES_SEED
    end

    def import_into_instruction_files
      %w[CLAUDE.md AGENTS.md].each { |file| marker_import(file) }
    end

    private

    def generated_rules
      registry = Poetry::Core::Registry.new(source_root: Poetry::Ui.root)
      body = Poetry::Core::LlmsText.new(registry: registry).full
      "<!-- generated by `rails g poetry:agent_rules` - DO NOT EDIT; " \
        "project overrides go in .poetry/house-rules.md -->\n\n#{body}"
    end

    def marker_import(relative)
      path = File.join(destination_root, relative)
      existing = File.exist?(path) ? File.read(path) : nil

      if existing.nil?
        create_file relative, IMPORT_BLOCK
      elsif existing.include?(START_MARKER) && existing.include?(END_MARKER)
        replaced = existing.sub(/#{Regexp.escape(START_MARKER)}.*?#{Regexp.escape(END_MARKER)}\n?/mo, IMPORT_BLOCK)
        create_file relative, replaced, force: true
      elsif existing.include?(START_MARKER) || existing.include?(END_MARKER)
        # Detect-but-never-rewrite: a half-marker means a human edited the
        # block - surface it, do not guess.
        say_status :conflict, "#{relative} has a broken poetry marker pair - fix it manually", :red
      else
        append_to_file relative, "\n#{IMPORT_BLOCK}"
      end
    end
  end
end
