# frozen_string_literal: true

# The committed template-class list: extracted with herb in poetry's CI,
# shipped in the gem so poetry:install never needs herb in a host. The
# browser pass (2026-07-01) caught sr-only/animate-spin being purged from
# host builds when the live scan was skipped.
TEMPLATE_CLASSES_HEADER =
  "# static template classes - generated by `bin/rake css:template_classes:generate`. DO NOT EDIT."

def poetry_ui_template_classes_text
  # Component templates + the block templates (Blocks v1): a block's
  # consumer utilities (group-has-*/sidebar-wrapper etc.) must reach host
  # safelists and the dummy's compiled build like any other gem markup.
  scans = ["app/components/**/*.html.erb", "lib/generators/poetry/block/templates/*.html.erb"].map do |glob|
    Poetry::Core::CSS::TemplateClasses.scan(root: Poetry::Ui.root, glob: glob)
  end
  abort scans.flat_map(&:errors).join("\n") unless scans.all? { |scan| scan.errors.empty? }

  ([TEMPLATE_CLASSES_HEADER] + scans.flat_map(&:classes).uniq.sort).join("\n") << "\n"
end

# The theme roster (N12): every themes/*.css fragment is a complete,
# installable visual theme. POETRY_THEME picks one for a single run
# (browser suites, an explicit gate); unset, the cheap gates loop over
# ALL themes so an incomplete fragment can never sit green in CI.
def poetry_ui_theme_names
  Dir[Poetry::Ui.root.join("themes/*.css").to_s].map { |file| File.basename(file, ".css") }.sort
end

def poetry_ui_theme_name = ENV.fetch("POETRY_THEME", "default")

def poetry_ui_theme_path(name = poetry_ui_theme_name)
  path = Poetry::Ui.root.join("themes/#{name}.css")
  abort "unknown poetry theme #{name.inspect} - poetry-ui ships: #{poetry_ui_theme_names.join(", ")}" unless path.exist?
  path
end

def poetry_ui_gate_themes
  ENV["POETRY_THEME"] ? [poetry_ui_theme_name] : poetry_ui_theme_names
end

# Compile the real Tailwind build a host's safelist produces: tokens +
# theme + vendored animate/shadcn utilities, sourced from the Style
# dictionaries plus the COMMITTED template classes. Shared by
# css:verify_compiled (the drift gate) and browser:assets (the stylesheet
# the real-browser preview pages load). extra_sources adds Tailwind
# @source dirs beyond the safelist - the benchmark capture (N15 W2) scans
# the generated arms so a raw arm's arbitrary utilities compile with full
# fidelity (no purge bias in the judge's evidence).
def poetry_ui_compile_tailwind(theme: poetry_ui_theme_name, extra_sources: [])
  require "tailwindcss/ruby"
  require "tmpdir"

  styles = Poetry::Core::Style.descendants.select(&:name)

  Dir.mktmpdir("poetry-css") do |dir|
    safelist = Poetry::Core::CSS::Safelist.new(style_classes: styles,
                                               template_classes: Poetry::Ui.template_classes)
    File.write(File.join(dir, "safelist.txt"), safelist.text)
    File.write(File.join(dir, "entry.css"), <<~CSS)
      @import "tailwindcss" source(none);
      @import "#{Poetry::Core.root.join("tokens/tokens.css")}";
      @import "#{Poetry::Core.root.join("tokens/tailwind-theme.css")}";
      @import "#{Poetry::Core.root.join("vendor/tw-animate-css/tw-animate.css")}";
      @import "#{Poetry::Core.root.join("vendor/shadcn-tailwind/tailwind.css")}";
      @import "#{Poetry::Core.root.join("tokens/aliases.css")}";
      @import "#{poetry_ui_theme_path(theme)}" layer(base);
      @import "#{Poetry::Ui.root.join("typeset/typeset.css")}";
      @source "#{File.join(dir, "safelist.txt")}";
      #{extra_sources.map { |src| %(@source "#{src}";) }.join("\n")}
    CSS
    out = File.join(dir, "out.css")
    system(Tailwindcss::Ruby.executable, "-i", File.join(dir, "entry.css"), "-o", out,
           exception: true, out: File::NULL, err: File::NULL)
    File.read(out)
  end
end

# Preview scaffolding classes (tag.div class strings, render_component
# class: args) live in preview.rb - host safelists rightly never see them,
# so the PREVIEW-rendering build sources the files directly (Tailwind's
# scanner reads any text file). component.rb is deliberately NOT sourced:
# css:verify_rendered's teeth depend on a component-emitted bare string
# staying uncompiled (the pagination pl-2! / combobox w-50 class).
def poetry_ui_preview_sources
  previews = Dir[Poetry::Ui.root.join("app/components/**/preview.rb").to_s]
  # Preview ERB templates and block templates join as RAW text sources:
  # the herb harvest extracts static class attributes only, so utility
  # strings inside helper kwargs (poetry_input(class: "col-span-2 h-8"))
  # are invisible to it. In a host the block copy compiles via the
  # host's own view scan; the gem's preview build needs the raw scan.
  preview_templates = Dir[Poetry::Ui.root.join("app/components/**/*preview*.html.erb").to_s]
  block_templates = Dir[Poetry::Ui.root.join("lib/generators/poetry/block/templates/*.html.erb").to_s]
  layout = Poetry::Ui.root.join("test/dummy/app/views/layouts/component_preview.html.erb")
  wrapper = Poetry::Core.root.join("app/views/poetry/core/preview.html.erb")
  (previews + preview_templates + block_templates + [layout.to_s, wrapper.to_s]).sort
end

# Runtime custom-property assignments, DERIVED from the actual sources -
# never a maintained list (, the kumo parseKumoSemanticColors lesson
# pointed verify-side):
#   - poetry-core JS: every bare "--name" string literal (setProperty args,
#     `property:` options, module constants) plus template-literal prefixes
#     for dynamic names (`--drawer-swipe-movement-${axis}` registers the
#     prefix, and any read under it resolves)
#   - gem templates/components + block templates: inline-style `--name:`
#     assignments (e.g. --poetry-tree-level), comment lines stripped first
#     so prose mentioning a var never counts as defining it
def poetry_ui_runtime_var_definitions
  js = Dir[Poetry::Core.root.join("app/javascript/**/*.js").to_s]
       .map { |file| File.read(file) }.join("\n")
  names = js.scan(/["'`](--[A-Za-z][\w-]*)["'`]/).flatten
  prefixes = js.scan(/`(--[A-Za-z][\w-]*-)\$\{/).flatten

  inline = poetry_ui_var_scan_sources.flat_map do |text|
    text.scan(Poetry::Core::CSS::VarCoverage::DECLARATION).flatten
  end
  [(names + inline).uniq, prefixes.uniq]
end

# var(--x) reads that live in inline styles / template attributes, which a
# compiled Tailwind build never sees (class-string reads DO compile via the
# safelist and are already covered by the build scan).
def poetry_ui_template_var_reads
  poetry_ui_var_scan_sources.flat_map do |text|
    text.scan(Poetry::Core::CSS::VarCoverage::READ).flatten
  end.uniq
end

def poetry_ui_var_scan_sources
  globs = ["app/components/**/*.rb", "app/components/**/*.erb",
           # Part helpers emit markup too - the sidebar skeleton writes its
           # --skeleton-width inline style from here (batch 8c).
           "app/helpers/**/*.rb",
           "lib/generators/poetry/block/templates/*.html.erb"]
  globs.flat_map { |glob| Dir[Poetry::Ui.root.join(glob).to_s] }.map do |file|
    File.read(file).lines.reject { |line| line.strip.start_with?("#", "<%#") }.join
  end
end

# Reads pinned inside VENDORED upstream CSS are upstream's contract, not
# poetry's: tw-animate keyframes target every ecosystem's accordion var
# (--radix-, --bits-, --kb-, --reka-...), and shadcn's shimmer/scroll-fade
# utilities read vars the CONSUMER sets inline. Derived from the vendor
# files themselves - a poetry-owned dead read (the class) never
# appears there, so the exemption cannot mask one.
def poetry_ui_vendored_var_reads
  Dir[Poetry::Core.root.join("vendor/**/*.css").to_s].flat_map do |file|
    File.read(file).scan(Poetry::Core::CSS::VarCoverage::READ).flatten
  end.uniq
end

namespace :css do
  namespace :template_classes do
    desc "Regenerate config/template_classes.txt from the gem's templates (herb)"
    task :generate do
      poetry_ui_boot!
      path = Poetry::Ui.root.join(Poetry::Ui::TEMPLATE_CLASSES_PATH)
      path.write(poetry_ui_template_classes_text)
      puts "regenerated #{path}"
    end

    desc "Fail if the committed template-class list does not match a fresh herb scan (the CI drift gate)"
    task :verify do
      poetry_ui_boot!
      path = Poetry::Ui.root.join(Poetry::Ui::TEMPLATE_CLASSES_PATH)
      if path.exist? && path.read == poetry_ui_template_classes_text
        puts "template classes in sync (#{Poetry::Ui::TEMPLATE_CLASSES_PATH})"
      else
        abort "stale template classes - run `bin/rake css:template_classes:generate` and commit"
      end
    end
  end
  desc "Compile a real Tailwind build (tokens + theme + vendored animate + safelist) and verify " \
       "every Style-dictionary class against it - the gate the fresh-app proof showed was missing " \
       "(Dialog shipped tw-animate-css classes nothing provided)"
  task :verify_compiled do
    poetry_ui_boot!

    styles = Poetry::Core::Style.descendants.select(&:name)

    # One compile per theme: a cn name a theme lacks cannot compile, so this
    # doubles as the port-completeness gate for every fragment (N12).
    poetry_ui_gate_themes.each do |theme|
      # The COMMITTED template classes (drift-gated by template_classes:verify),
      # so this build is byte-for-byte what a host's safelist produces.
      compiled = poetry_ui_compile_tailwind(theme: theme)

      verifier = Poetry::Core::CSS::Verifier.new(compiled_css: compiled)
      failures = styles.flat_map do |style|
        verifier.verify_style(style).map { |unknown| "#{style.name}: #{unknown}" }
      end
      abort "classes missing from a real Tailwind build (theme #{theme}):\n#{failures.join("\n")}" if failures.any?

      # Tripwire floor: scanning zero dictionaries is a broken eager-load,
      # not a pass.
      abort "tripwire: 0 Style dictionaries scanned (eager load broken?)" if styles.empty?
      puts "all #{styles.size} Style dictionaries verified against a compiled Tailwind build (theme #{theme})"
    end
  end

  desc "Render every preview and verify each rendered class token exists in the compiled " \
       "preview build (safelist + preview sources) - the rendered-truth gate for the " \
       "'utilities live where the harvest sees them' rule (the pagination pl-2! / " \
       "combobox w-50 class of bug)"
  task :verify_rendered do
    poetry_ui_boot!
    require "nokogiri"

    compiled = poetry_ui_compile_tailwind(extra_sources: poetry_ui_preview_sources)
    verifier = Poetry::Core::CSS::Verifier.new(compiled_css: compiled)

    session = ActionDispatch::Integration::Session.new(Rails.application)
    # token -> "url <tag>" of its first sighting, so a failure names the
    # page and element that emitted it.
    tokens = {}
    pages = poetry_ui_preview_pages
    pages.each do |_component, _example, url|
      session.get(url)
      abort "HTTP #{session.response.status} at #{url}" unless session.response.successful?

      Nokogiri::HTML(session.response.body).css("[class]").each do |element|
        # Rouge token spans inside <pre> (code_block / typeset highlighting)
        # carry the syntax palette's semantic classes (n, p, k...) - the
        # theme's contract, not Tailwind utilities.
        next if element.ancestors.any? { |ancestor| ancestor.name == "pre" }

        element["class"].split(/\s+/).each { |token| tokens[token] ||= "#{url} <#{element.name}>" }
      end
    end

    failures = verifier.unknown(tokens.keys.sort)
    if failures.any?
      report = failures.map { |unknown| "#{unknown} - first seen #{tokens[unknown.class_name]}" }
      abort "rendered class tokens missing from the compiled preview build - a component or " \
            "preview emits a utility no harvest ships (move it into a Style dictionary or " \
            "preview source):\n  #{report.join("\n  ")}"
    end

    abort "tripwire: rendered-class scan saw no preview pages" if pages.empty?
    abort "tripwire: rendered-class scan harvested no tokens" if tokens.empty?
    puts "rendered-class coverage: #{tokens.size} tokens across #{pages.size} preview pages " \
         "all present in the compiled build"
  end

  desc "Verify bidirectional cn-* coverage between the Style dictionaries and every themes/*.css (N11/N12)"
  task :verify_theme do
    poetry_ui_boot!

    styles = Poetry::Core::Style.descendants.select(&:name)
    poetry_ui_gate_themes.each do |theme|
      coverage = Poetry::Core::CSS::ThemeCoverage.new(
        theme_css: poetry_ui_theme_path(theme).read,
        style_classes: styles,
        # Consumer utilities: applied by templates/consumers, not emitted by
        # any dictionary (cn-font-heading IS emitted by Empty, listed for
        # robustness; cn-rtl-flip is template-side only). Every theme must
        # carry them - they are part of the fragment contract.
        allowlist: %w[cn-font-heading cn-rtl-flip]
      )

      # One direction only: dictionary names missing a theme rule. The
      # orphan direction (theme rules nothing wears) moved to
      # css:verify_hooks - its scan sees component-code and helper-string
      # emissions plus the hook_coverage.yml interpolated list, which this
      # dictionary-only pass cannot (the 14 false orphans of 2026-08-14).
      problems = coverage.missing.map { |name| "missing theme rule: #{name}" }
      abort "theme coverage (themes/#{theme}.css):\n  #{problems.join("\n  ")}" unless problems.empty?

      abort "tripwire: theme coverage scanned no cn rules (theme CSS missing?)" if coverage.theme_names.empty?
      puts "theme coverage (#{theme}): #{coverage.theme_names.size} cn rules <-> " \
           "#{coverage.dictionary_names.size} dictionary names"
    end
  end

  desc "Verify every var(--x) read resolves to a definition - compiled declarations, @property " \
       "registrations, or runtime assignments derived from the real JS/template sources (; " \
       "the class of bug dug out by hand as 13 dead --radix-* reads)"
  task :verify_vars do
    poetry_ui_boot!

    runtime_names, runtime_prefixes = poetry_ui_runtime_var_definitions
    template_reads = poetry_ui_template_var_reads

    # The ONLY hand-maintained entries; each carries its reason.
    #   --font-heading: the documented consumer hook - a host defines it to
    #   opt into a heading font; cn-font-heading falls back to --font-sans
    #   (themes/*.css) - definition-free in the gem BY CONTRACT.
    consumer_hooks = %w[--font-heading]
    # Tailwind's own namespaces (--tw-* internals + preflight's optional
    # --default-* font hooks) are the toolchain's contract.
    toolchain_prefixes = %w[--tw --default-]

    poetry_ui_gate_themes.each do |theme|
      coverage = Poetry::Core::CSS::VarCoverage.new(
        compiled_css: poetry_ui_compile_tailwind(theme: theme),
        extra_definitions: runtime_names + poetry_ui_vendored_var_reads + consumer_hooks,
        definition_prefixes: runtime_prefixes + toolchain_prefixes,
        extra_reads: template_reads
      )

      if coverage.dead_reads.any?
        abort "dead var() reads (theme #{theme}) - read somewhere, defined nowhere " \
              "(build, @property, JS setProperty, inline style):\n  #{coverage.dead_reads.join("\n  ")}"
      end

      abort "tripwire: var coverage scanned no reads (source scan broken?)" if coverage.reads.empty?
      puts "var coverage (#{theme}): #{coverage.reads.size} reads resolve against " \
           "#{coverage.definitions.size} definitions (+#{runtime_names.size} runtime, " \
           "#{runtime_prefixes.size} dynamic prefixes)"
    end
  end

  # The data-selected bridge probe (N6 W1 regression lock): upstream's
  # vendored variant matches only [data-selected="true"], poetry emits BARE
  # presence, and tokens/aliases.css redefines the variant to cover both
  # (Tailwind @custom-variant redefinition is last-wins). If an import
  # reorder or a Tailwind change ever flips which definition wins, consumer
  # data-selected:* classes would silently stop matching poetry's emission
  # - this compiles a probe class and asserts poetry's selector form won.
  desc "Verify the extended data-selected bridge variant survives the compile"
  task :verify_selected_bridge do
    poetry_ui_boot!
    require "tailwindcss/ruby"
    require "tmpdir"

    compiled = Dir.mktmpdir("poetry-bridge-probe") do |dir|
      File.write(File.join(dir, "probe.txt"), "data-selected:underline\n")
      File.write(File.join(dir, "entry.css"), <<~CSS)
        @import "tailwindcss";
        @import "#{Poetry::Core.root.join("vendor/shadcn-tailwind/tailwind.css")}";
        @import "#{Poetry::Core.root.join("tokens/aliases.css")}";
        @source "#{File.join(dir, "probe.txt")}";
      CSS
      out = File.join(dir, "out.css")
      system(Tailwindcss::Ruby.executable, "-i", File.join(dir, "entry.css"), "-o", out,
             exception: true, out: File::NULL, err: File::NULL)
      File.read(out)
    end

    unless compiled.include?('[data-selected]:not([data-selected="false"])')
      abort "data-selected bridge probe FAILED: poetry's extended variant (bare presence + " \
            "=\"true\") did not win the compile - check tokens/aliases.css import order"
    end

    puts "data-selected bridge variant verified (poetry's last-wins extension holds)"
  end

  # The compiled-artifact reduced-motion contract: the vendored
  # @media (prefers-reduced-motion: reduce) shimmer kill must survive a
  # real host compile (import flattening or a minifier rewrite would
  # silently ship motion to users who asked for none - the preview rig's
  # CDP emulation only proves the TEST pages honor it).
  desc "Verify the reduced-motion block survives a real Tailwind compile"
  task :verify_reduced_motion do
    poetry_ui_boot!
    require "tailwindcss/ruby"
    require "tmpdir"

    compiled = Dir.mktmpdir("poetry-motion-probe") do |dir|
      File.write(File.join(dir, "probe.txt"), "shimmer\n")
      File.write(File.join(dir, "entry.css"), <<~CSS)
        @import "tailwindcss";
        @import "#{Poetry::Core.root.join("vendor/shadcn-tailwind/tailwind.css")}";
        @import "#{Poetry::Core.root.join("tokens/aliases.css")}";
        @source "#{File.join(dir, "probe.txt")}";
      CSS
      out = File.join(dir, "out.css")
      system(Tailwindcss::Ruby.executable, "-i", File.join(dir, "entry.css"), "-o", out,
             exception: true, out: File::NULL, err: File::NULL)
      File.read(out)
    end

    blocks = compiled.scan(/@media \(prefers-reduced-motion: reduce\)\s*\{(.*?)\n\}/m).flatten
    shimmer_kill = blocks.any? { |block| block.match?(/\.shimmer\s*\{[^}]*animation:\s*none/m) }

    unless shimmer_kill
      abort "reduced-motion probe FAILED: the vendored shimmer kill did not survive the " \
            "compile - check the vendor import chain / minifier settings"
    end

    puts "reduced-motion contract verified in the compiled artifact (shimmer kill present)"
  end
end
