# frozen_string_literal: true

# The committed template-class list: extracted with herb in poetry's CI,
# shipped in the gem so poetry:install never needs herb in a host. The
# browser pass (2026-07-01) caught sr-only/animate-spin being purged from
# host builds when the live scan was skipped.
TEMPLATE_CLASSES_HEADER =
  "# static template classes - generated by `bin/rake css:template_classes:generate`. DO NOT EDIT."

def poetry_ui_template_classes_text
  templates = Poetry::Core::CSS::TemplateClasses.scan(root: Poetry::Ui.root)
  abort templates.errors.join("\n") unless templates.errors.empty?

  ([TEMPLATE_CLASSES_HEADER] + templates.classes).join("\n") << "\n"
end

# Compile the real Tailwind build a host's safelist produces: tokens +
# theme + vendored animate/shadcn utilities, sourced from the Style
# dictionaries plus the COMMITTED template classes. Shared by
# css:verify_compiled (the drift gate) and browser:assets (the stylesheet
# the real-browser preview pages load).
def poetry_ui_compile_tailwind
  require "tailwindcss/ruby"
  require "tmpdir"

  styles = Poetry::Core::Style.descendants.select(&:name)

  Dir.mktmpdir("poetry-css") do |dir|
    safelist = Poetry::Core::CSS::Safelist.new(style_classes: styles,
                                               template_classes: Poetry::Ui.template_classes)
    File.write(File.join(dir, "safelist.txt"), safelist.text)
    File.write(File.join(dir, "entry.css"), <<~CSS)
      @import "tailwindcss";
      @import "#{Poetry::Core.root.join("tokens/tokens.css")}";
      @import "#{Poetry::Core.root.join("tokens/tailwind-theme.css")}";
      @import "#{Poetry::Core.root.join("vendor/tw-animate-css/tw-animate.css")}";
      @import "#{Poetry::Core.root.join("vendor/shadcn-tailwind/tailwind.css")}";
      @import "#{Poetry::Core.root.join("tokens/aliases.css")}";
      @import "#{Poetry::Ui.root.join("themes/default.css")}" layer(base);
      @source "#{File.join(dir, "safelist.txt")}";
    CSS
    out = File.join(dir, "out.css")
    system(Tailwindcss::Ruby.executable, "-i", File.join(dir, "entry.css"), "-o", out,
           exception: true, out: File::NULL, err: File::NULL)
    File.read(out)
  end
end

namespace :css do
  namespace :template_classes do
    desc "Regenerate config/template_classes.txt from the gem's templates (herb)"
    task :generate do
      poetry_ui_boot!
      path = Poetry::Ui.root.join(Poetry::Ui::TEMPLATE_CLASSES_PATH)
      path.write(poetry_ui_template_classes_text)
      puts "regenerated #{path}"
    end

    desc "Fail if the committed template-class list does not match a fresh herb scan (the CI drift gate)"
    task :verify do
      poetry_ui_boot!
      path = Poetry::Ui.root.join(Poetry::Ui::TEMPLATE_CLASSES_PATH)
      if path.exist? && path.read == poetry_ui_template_classes_text
        puts "template classes in sync (#{Poetry::Ui::TEMPLATE_CLASSES_PATH})"
      else
        abort "stale template classes - run `bin/rake css:template_classes:generate` and commit"
      end
    end
  end
  desc "Compile a real Tailwind build (tokens + theme + vendored animate + safelist) and verify " \
       "every Style-dictionary class against it - the gate the fresh-app proof showed was missing " \
       "(Dialog shipped tw-animate-css classes nothing provided)"
  task :verify_compiled do
    poetry_ui_boot!

    # The COMMITTED template classes (drift-gated by template_classes:verify),
    # so this build is byte-for-byte what a host's safelist produces.
    compiled = poetry_ui_compile_tailwind
    styles = Poetry::Core::Style.descendants.select(&:name)

    verifier = Poetry::Core::CSS::Verifier.new(compiled_css: compiled)
    failures = styles.flat_map do |style|
      verifier.verify_style(style).map { |unknown| "#{style.name}: #{unknown}" }
    end
    abort "classes missing from a real Tailwind build:\n#{failures.join("\n")}" if failures.any?

    puts "all #{styles.size} Style dictionaries verified against a compiled Tailwind build"
  end

  desc "Verify bidirectional cn-* coverage between the Style dictionaries and themes/default.css (N11)"
  task :verify_theme do
    poetry_ui_boot!

    styles = Poetry::Core::Style.descendants.select(&:name)
    coverage = Poetry::Core::CSS::ThemeCoverage.new(
      theme_css: Poetry::Ui.root.join("themes/default.css").read,
      style_classes: styles,
      allowlist: [] # consumer utility classes (cn-font-heading, cn-rtl-flip) arrive at W4
    )

    problems = coverage.missing.map { |name| "missing theme rule: #{name}" } +
               coverage.orphans.map { |name| "orphan theme rule: #{name}" }
    abort "theme coverage (themes/default.css):\n  #{problems.join("\n  ")}" unless problems.empty?

    puts "theme coverage: #{coverage.theme_names.size} cn rules <-> " \
         "#{coverage.dictionary_names.size} dictionary names"
  end

  # The data-selected bridge probe (N6 W1 regression lock): upstream's
  # vendored variant matches only [data-selected="true"], poetry emits BARE
  # presence, and tokens/aliases.css redefines the variant to cover both
  # (Tailwind @custom-variant redefinition is last-wins). If an import
  # reorder or a Tailwind change ever flips which definition wins, consumer
  # data-selected:* classes would silently stop matching poetry's emission
  # - this compiles a probe class and asserts poetry's selector form won.
  desc "Verify the extended data-selected bridge variant survives the compile"
  task :verify_selected_bridge do
    poetry_ui_boot!
    require "tailwindcss/ruby"
    require "tmpdir"

    compiled = Dir.mktmpdir("poetry-bridge-probe") do |dir|
      File.write(File.join(dir, "probe.txt"), "data-selected:underline\n")
      File.write(File.join(dir, "entry.css"), <<~CSS)
        @import "tailwindcss";
        @import "#{Poetry::Core.root.join("vendor/shadcn-tailwind/tailwind.css")}";
        @import "#{Poetry::Core.root.join("tokens/aliases.css")}";
        @source "#{File.join(dir, "probe.txt")}";
      CSS
      out = File.join(dir, "out.css")
      system(Tailwindcss::Ruby.executable, "-i", File.join(dir, "entry.css"), "-o", out,
             exception: true, out: File::NULL, err: File::NULL)
      File.read(out)
    end

    unless compiled.include?('[data-selected]:not([data-selected="false"])')
      abort "data-selected bridge probe FAILED: poetry's extended variant (bare presence + " \
            "=\"true\") did not win the compile - check tokens/aliases.css import order"
    end

    puts "data-selected bridge variant verified (poetry's last-wins extension holds)"
  end
end
