# frozen_string_literal: true

# The committed template-class list: extracted with herb in poetry's CI,
# shipped in the gem so poetry:install never needs herb in a host. The
# browser pass (2026-07-01) caught sr-only/animate-spin being purged from
# host builds when the live scan was skipped.
TEMPLATE_CLASSES_HEADER =
  "# static template classes - generated by `bin/rake css:template_classes:generate`. DO NOT EDIT."

def poetry_ui_template_classes_text
  # Component templates + the block templates (Blocks v1): a block's
  # consumer utilities (group-has-*/sidebar-wrapper etc.) must reach host
  # safelists and the dummy's compiled build like any other gem markup.
  scans = ["app/components/**/*.html.erb", "lib/generators/poetry/block/templates/*.html.erb"].map do |glob|
    Poetry::Core::CSS::TemplateClasses.scan(root: Poetry::Ui.root, glob: glob)
  end
  abort scans.flat_map(&:errors).join("\n") unless scans.all? { |scan| scan.errors.empty? }

  ([TEMPLATE_CLASSES_HEADER] + scans.flat_map(&:classes).uniq.sort).join("\n") << "\n"
end

# The theme roster (N12): every themes/*.css fragment is a complete,
# installable visual theme. POETRY_THEME picks one for a single run
# (browser suites, an explicit gate); unset, the cheap gates loop over
# ALL themes so an incomplete fragment can never sit green in CI.
def poetry_ui_theme_names
  Dir[Poetry::Ui.root.join("themes/*.css").to_s].map { |file| File.basename(file, ".css") }.sort
end

def poetry_ui_theme_name = ENV.fetch("POETRY_THEME", "default")

def poetry_ui_theme_path(name = poetry_ui_theme_name)
  path = Poetry::Ui.root.join("themes/#{name}.css")
  abort "unknown poetry theme #{name.inspect} - poetry-ui ships: #{poetry_ui_theme_names.join(", ")}" unless path.exist?
  path
end

def poetry_ui_gate_themes
  ENV["POETRY_THEME"] ? [poetry_ui_theme_name] : poetry_ui_theme_names
end

# Compile the real Tailwind build a host's safelist produces: tokens +
# theme + vendored animate/shadcn utilities, sourced from the Style
# dictionaries plus the COMMITTED template classes. Shared by
# css:verify_compiled (the drift gate) and browser:assets (the stylesheet
# the real-browser preview pages load). extra_sources adds Tailwind
# @source dirs beyond the safelist - the benchmark capture (N15 W2) scans
# the generated arms so a raw arm's arbitrary utilities compile with full
# fidelity (no purge bias in the judge's evidence).
def poetry_ui_compile_tailwind(theme: poetry_ui_theme_name, extra_sources: [])
  require "tailwindcss/ruby"
  require "tmpdir"

  styles = Poetry::Core::Style.descendants.select(&:name)

  Dir.mktmpdir("poetry-css") do |dir|
    safelist = Poetry::Core::CSS::Safelist.new(style_classes: styles,
                                               template_classes: Poetry::Ui.template_classes)
    File.write(File.join(dir, "safelist.txt"), safelist.text)
    File.write(File.join(dir, "entry.css"), <<~CSS)
      @import "tailwindcss";
      @import "#{Poetry::Core.root.join("tokens/tokens.css")}";
      @import "#{Poetry::Core.root.join("tokens/tailwind-theme.css")}";
      @import "#{Poetry::Core.root.join("vendor/tw-animate-css/tw-animate.css")}";
      @import "#{Poetry::Core.root.join("vendor/shadcn-tailwind/tailwind.css")}";
      @import "#{Poetry::Core.root.join("tokens/aliases.css")}";
      @import "#{poetry_ui_theme_path(theme)}" layer(base);
      @source "#{File.join(dir, "safelist.txt")}";
      #{extra_sources.map { |src| %(@source "#{src}";) }.join("\n")}
    CSS
    out = File.join(dir, "out.css")
    system(Tailwindcss::Ruby.executable, "-i", File.join(dir, "entry.css"), "-o", out,
           exception: true, out: File::NULL, err: File::NULL)
    File.read(out)
  end
end

namespace :css do
  namespace :template_classes do
    desc "Regenerate config/template_classes.txt from the gem's templates (herb)"
    task :generate do
      poetry_ui_boot!
      path = Poetry::Ui.root.join(Poetry::Ui::TEMPLATE_CLASSES_PATH)
      path.write(poetry_ui_template_classes_text)
      puts "regenerated #{path}"
    end

    desc "Fail if the committed template-class list does not match a fresh herb scan (the CI drift gate)"
    task :verify do
      poetry_ui_boot!
      path = Poetry::Ui.root.join(Poetry::Ui::TEMPLATE_CLASSES_PATH)
      if path.exist? && path.read == poetry_ui_template_classes_text
        puts "template classes in sync (#{Poetry::Ui::TEMPLATE_CLASSES_PATH})"
      else
        abort "stale template classes - run `bin/rake css:template_classes:generate` and commit"
      end
    end
  end
  desc "Compile a real Tailwind build (tokens + theme + vendored animate + safelist) and verify " \
       "every Style-dictionary class against it - the gate the fresh-app proof showed was missing " \
       "(Dialog shipped tw-animate-css classes nothing provided)"
  task :verify_compiled do
    poetry_ui_boot!

    styles = Poetry::Core::Style.descendants.select(&:name)

    # One compile per theme: a cn name a theme lacks cannot compile, so this
    # doubles as the port-completeness gate for every fragment (N12).
    poetry_ui_gate_themes.each do |theme|
      # The COMMITTED template classes (drift-gated by template_classes:verify),
      # so this build is byte-for-byte what a host's safelist produces.
      compiled = poetry_ui_compile_tailwind(theme: theme)

      verifier = Poetry::Core::CSS::Verifier.new(compiled_css: compiled)
      failures = styles.flat_map do |style|
        verifier.verify_style(style).map { |unknown| "#{style.name}: #{unknown}" }
      end
      abort "classes missing from a real Tailwind build (theme #{theme}):\n#{failures.join("\n")}" if failures.any?

      puts "all #{styles.size} Style dictionaries verified against a compiled Tailwind build (theme #{theme})"
    end
  end

  desc "Verify bidirectional cn-* coverage between the Style dictionaries and every themes/*.css (N11/N12)"
  task :verify_theme do
    poetry_ui_boot!

    styles = Poetry::Core::Style.descendants.select(&:name)
    poetry_ui_gate_themes.each do |theme|
      coverage = Poetry::Core::CSS::ThemeCoverage.new(
        theme_css: poetry_ui_theme_path(theme).read,
        style_classes: styles,
        # Consumer utilities: applied by templates/consumers, not emitted by
        # any dictionary (cn-font-heading IS emitted by Empty, listed for
        # robustness; cn-rtl-flip is template-side only). Every theme must
        # carry them - they are part of the fragment contract.
        allowlist: %w[cn-font-heading cn-rtl-flip]
      )

      problems = coverage.missing.map { |name| "missing theme rule: #{name}" } +
                 coverage.orphans.map { |name| "orphan theme rule: #{name}" }
      abort "theme coverage (themes/#{theme}.css):\n  #{problems.join("\n  ")}" unless problems.empty?

      puts "theme coverage (#{theme}): #{coverage.theme_names.size} cn rules <-> " \
           "#{coverage.dictionary_names.size} dictionary names"
    end
  end

  # The data-selected bridge probe (N6 W1 regression lock): upstream's
  # vendored variant matches only [data-selected="true"], poetry emits BARE
  # presence, and tokens/aliases.css redefines the variant to cover both
  # (Tailwind @custom-variant redefinition is last-wins). If an import
  # reorder or a Tailwind change ever flips which definition wins, consumer
  # data-selected:* classes would silently stop matching poetry's emission
  # - this compiles a probe class and asserts poetry's selector form won.
  desc "Verify the extended data-selected bridge variant survives the compile"
  task :verify_selected_bridge do
    poetry_ui_boot!
    require "tailwindcss/ruby"
    require "tmpdir"

    compiled = Dir.mktmpdir("poetry-bridge-probe") do |dir|
      File.write(File.join(dir, "probe.txt"), "data-selected:underline\n")
      File.write(File.join(dir, "entry.css"), <<~CSS)
        @import "tailwindcss";
        @import "#{Poetry::Core.root.join("vendor/shadcn-tailwind/tailwind.css")}";
        @import "#{Poetry::Core.root.join("tokens/aliases.css")}";
        @source "#{File.join(dir, "probe.txt")}";
      CSS
      out = File.join(dir, "out.css")
      system(Tailwindcss::Ruby.executable, "-i", File.join(dir, "entry.css"), "-o", out,
             exception: true, out: File::NULL, err: File::NULL)
      File.read(out)
    end

    unless compiled.include?('[data-selected]:not([data-selected="false"])')
      abort "data-selected bridge probe FAILED: poetry's extended variant (bare presence + " \
            "=\"true\") did not win the compile - check tokens/aliases.css import order"
    end

    puts "data-selected bridge variant verified (poetry's last-wins extension holds)"
  end
end
