# frozen_string_literal: true

require "test_helper"
require "rails/generators"
require "rails/generators/test_case"
require "generators/poetry/block/block_generator"

module Poetry
  class BlockGeneratorTest < Rails::Generators::TestCase
    tests Poetry::BlockGenerator
    destination File.expand_path("../tmp/block-dest", __dir__)
    setup :prepare_destination

    def test_copies_a_block_as_app_owned_source_with_the_ownership_header
      run_generator ["data-index"]

      assert_file "app/views/blocks/_data_index.html.erb" do |content|
        assert content.start_with?("<%# generated by `bin/rails g poetry:block data-index`"),
               "the metadata header is rewritten to an ownership note"
        refute_match(/poetry:block title=/, content, "the source metadata header does not ship")
        assert_match(/poetry_table_body/, content, "the composed body ships verbatim")
        assert_match(/poetry_pagination/, content)
      end
    end

    def test_accepts_underscored_names_and_normalizes
      run_generator ["app_shell"]

      assert_file "app/views/blocks/_app_shell.html.erb" do |content|
        assert_match(/poetry_sidebar\b/, content)
        assert_match(%r{group-has-data-\[collapsible=icon\]/sidebar-wrapper},
                     content, "the topbar ships the sidebar-wrapper marker consumer")
      end
    end

    def test_unknown_block_fails_loudly_with_the_catalog
      # The generator runner reports Thor::Error rather than raising it -
      # the receipt is the message plus the absence of any created file.
      output = run_generator ["no-such-block"]

      assert_match(/unknown block/, output)
      assert_match(/data-index/, output, "the failure prints the catalog")
      assert_no_file "app/views/blocks/_no_such_block.html.erb"
    end

    def test_every_registry_block_copies_and_carries_no_metadata_header
      registry = YAML.safe_load_file(Poetry::Ui.root.join(Poetry::Core::Registry::RELATIVE_PATH))

      registry.fetch("blocks").each_key do |name|
        run_generator [name]

        assert_file "app/views/blocks/_#{name.tr("-", "_")}.html.erb" do |content|
          refute_match(/poetry:block title=/, content)
        end
      end
    end

    # The one generator template carrying Stimulus wiring: every
    # hand-written token must stay manifest-valid (the template generates
    # into HOST apps, where poetry check re-validates - this pins it at
    # the source).
    test "action_bar template wiring is manifest-valid" do
      template = File.read(File.expand_path(
                             "../../lib/generators/poetry/block/templates/action_bar.html.erb", __dir__
                           ))
      identifier = "poetry--core--action-bar"
      definition = Poetry::Core::Stimulus::Manifest.definition(identifier)

      assert definition, "action-bar controller missing from the manifest"
      assert_includes template, %(data-controller="#{identifier}")
      template.scan(/data-action="([^"]+)"/).flatten.flat_map(&:split).each do |token|
        next unless token.include?(identifier)

        method = token.split("#").last

        assert_includes definition["methods"], method, "unknown action method #{method}"
      end
      template.scan(/data-#{identifier}-target="([^"]+)"/).flatten.each do |target|
        assert_includes definition["targets"], target, "unknown target #{target}"
      end
      template.scan(/data-#{identifier}-([a-z-]+)-value=/).flatten.each do |key|
        camel = key.split("-").each_with_index.map { |part, i| i.zero? ? part : part.capitalize }.join

        assert_includes definition["values"].keys, camel, "unknown value #{key}"
      end
    end
  end
end
