# frozen_string_literal: true

#
# N12 theme-port tooling: the generalized fragment writer (W2). The W1
# original, writer.rb, stays byte-frozen as the vega artifact - this
# engine does the same job for any theme, driven by a per-theme plan
# file. See the theme-port plan.
#
# Run: cd Code/poetry-ui && bundle exec ruby script/theme_port/write_theme.rb <theme>
#
# Loads script/theme_port/plans/<theme>.rb, which must define:
#   PLAN   - { "cn-name" => value } where value is
#            :default              keep poetry's default body (poetry-own idiom)
#            :upstream_sub_content transplant upstream's *-sub-content body onto
#                                  poetry's one-word subcontent name
#            String                explicit body (judged)
#            {base:, drop:, add:, sub:}  base :upstream|:default, then edits
#   HEADER - the fragment's leading comment block
# Reads parts-<theme>.json (detector.rb output). Emits themes/<theme>.css
# from default.css structure and docs/<theme>-port-ledger.txt.
#
# ONE-SHOT: a shipped fragment is canonical and hand-edited (AA holds,
# hook rules) - the existing-file guard is the doctrine, not a hint.

require "json"

DIR = __dir__
UI = File.expand_path("../..", DIR)
THEME = ARGV.fetch(0) { abort "usage: write_theme.rb <theme>" }

target = File.join(UI, "themes/#{THEME}.css")
if File.exist?(target) && ENV["FORCE"] != "1"
  abort "themes/#{THEME}.css already exists - shipped fragments are canonical and hand-edited; " \
        "refusing to regenerate (FORCE=1 only for an unshipped draft)"
end

parts_path = File.join(DIR, "parts-#{THEME}.json")
abort "missing #{parts_path} - run detector.rb #{THEME} first" unless File.exist?(parts_path)
parts = JSON.parse(File.read(parts_path))
SHARED = parts["shared"]
UPSTREAM_RAW = parts["upstream_only"]

plan_path = File.join(DIR, "plans/#{THEME}.rb")
abort "missing #{plan_path} - author the per-theme PLAN + HEADER first" unless File.exist?(plan_path)
require plan_path
abort "#{plan_path} must define PLAN and HEADER" unless defined?(PLAN) && defined?(HEADER)

default_text = File.read(File.join(UI, "themes/default.css"))

WARNINGS = [] # rubocop:disable Style/MutableConstant -- accumulator, appended in upstream_body

def upstream_body(name, plan_value)
  entry = SHARED[name]
  case plan_value
  when nil
    return entry["rule"].join(" ") if entry && entry["status"] == "identical"
    return (entry["upstream"] - entry["dup_inline"]).join(" ") if entry # mechanical

    nil # poetry-only, no plan -> keep default
  when String then plan_value
  when :default, :upstream_sub_content then nil # sub_content handled by caller
  when Hash
    base = if plan_value[:base] == :upstream
             entry["upstream"] - (entry["dup_inline"] || [])
           else
             entry["rule"] || entry["default"]
           end
    base = base ? base.dup : []
    Array(plan_value[:drop]).each do |token|
      WARNINGS << "#{name}: drop target #{token.inspect} not in base" unless base.include?(token)
      base.delete(token)
    end
    base += Array(plan_value[:add])
    body = base.join(" ")
    (plan_value[:sub] || {}).each do |from, to|
      WARNINGS << "#{name}: sub source #{from.inspect} not found" unless body.include?(from)
      body = body.sub(from, to)
    end
    body
  end
end

out = +""
out << HEADER << "\n"

mode = :copy
skipped_header = false
default_text.each_line do |line| # rubocop:disable Metrics/BlockLength
  # drop default.css's own header comment (first comment block)
  unless skipped_header
    next if line.start_with?("/*", " *")

    skipped_header = true
    next if line.strip.empty?
  end

  case mode
  when :copy
    if (m = line.match(/\A\.(cn-[a-z0-9-]+)\s*\{\s*\z/))
      name = m[1]
      body = if PLAN[name] == :upstream_sub_content
               base = name.sub("subcontent", "sub-content")
               UPSTREAM_RAW[base].join(" ")
             else
               upstream_body(name, PLAN[name])
             end
      if body
        out << ".#{name} {\n  @apply #{body};\n}\n"
        mode = :skip_rule
      else
        out << line
        mode = :in_rule
      end
    else
      out << line
    end
  when :in_rule
    out << line
    mode = :copy if line.strip == "}"
  when :skip_rule
    mode = :copy if line.strip == "}"
  end
end

File.write(target, out)
puts "wrote #{target} (#{out.lines.size} lines)"

# --- ledger ---------------------------------------------------------------
ledger = "# N12 #{THEME} translation ledger (generated by write_theme.rb)\n\n"
SHARED.sort.each do |n, e|
  status = if PLAN[n].is_a?(String) || PLAN[n].is_a?(Hash) || PLAN[n] == :upstream_sub_content
             "judged"
           elsif PLAN[n] == :default
             "poetry-idiom (kept default)"
           elsif e["status"] == "identical"
             "identical"
           else
             "mechanical (#{THEME} minus inline dups)"
           end
  ledger << "#{n}: #{status}\n"
end
ledger << "\n## #{THEME}-only names (dropped; reason class)\n"
UPSTREAM_RAW.keys.sort.each { |n| ledger << "#{n}: dropped\n" }
File.write(File.join(UI, "docs/#{THEME}-port-ledger.txt"), ledger)
puts "ledger written to docs/#{THEME}-port-ledger.txt"

unless WARNINGS.empty?
  puts "\nPLAN drift warnings (verify each against style-#{THEME}.css):"
  WARNINGS.each { |w| puts "  #{w}" }
end
