# frozen_string_literal: true

module Poetry
  module Ui
    # The reset floor: Tailwind's preflight, rule for rule, at zero
    # specificity. Poetry's components lean on a handful of preflight's
    # normalizations (the universal border/padding reset, transparent
    # form controls, inherited heading sizes, collapsed tables, hidden
    # `[hidden]`) - measured: without preflight, two thirds of the golden
    # corpus renders differently even behind a modern reset. A host that
    # imports Tailwind without preflight installs this floor instead
    # (`poetry:install --no-preflight`), and every selector is wrapped in
    # `:where()`, so the floor only fills what nothing else declared: an
    # unlayered host rule always wins, and a host rule inside `layer(base)`
    # wins when it comes after the floor's import (same layer, same zero
    # specificity, later wins - a universal `*` rule imported before the
    # floor loses to it). `[hidden]` keeps preflight's `!important` on
    # purpose, so `hidden` stays hidden under any utility. Pseudo-element
    # selectors cannot be wrapped (`:where(::placeholder)` is invalid) and
    # keep their specificity.
    #
    # Generated from the pinned tailwindcss binary's own preflight
    # (`bin/rake reset:generate`), so the floor can never drift from the
    # preflight it stands in for; `reset:verify` is the CI gate. The
    # no-preflight visual pass (`POETRY_PREFLIGHT=0 rake test:visual`)
    # proves the floor against the golden corpus.
    #
    # @example The entry line the installer writes
    #   @import "./poetry/reset.css" layer(base);
    #
    # @api private
    module ResetFloor
      # Where the generated floor lives, relative to the gem root.
      RELATIVE_PATH = "reset/reset.css"

      HEADER = <<~CSS
        /* poetry reset floor - Tailwind's preflight at zero specificity.
           Generated by `bin/rake reset:generate` from the pinned tailwindcss binary; DO NOT EDIT
           (`rake reset:verify` fails when stale). Every selector is :where()-wrapped, so your own
           unlayered rule always wins, a rule in layer(base) wins after this import; this file only fills what nothing
           else declared. Pseudo-element selectors cannot be wrapped and keep their specificity.
           Tailwind CSS is MIT-licensed (see THIRD_PARTY_NOTICES.md). */
      CSS

      # Tailwind's full entry (preflight included) and the split entry that
      # leaves preflight out - what `poetry:install --no-preflight` writes
      # on a fresh entry, and the shape `entry_state` recognizes.
      PREFLIGHT_IMPORT = /^\s*@import\s+["']tailwindcss["']/
      FLOOR_IMPORT = %r{^\s*@import\s+["']\./poetry/reset\.css["']}
      NO_PREFLIGHT_ENTRY = <<~CSS
        @layer theme, base, components, utilities;
        @import "tailwindcss/theme.css" layer(theme);
        @import "tailwindcss/utilities.css" layer(utilities);
      CSS

      module_function

      # Preflight as the pinned tailwindcss binary compiles it (with the
      # theme referenced, so font stacks keep their `var(--default-font-family, ...)`
      # form and a host's `@theme` fonts apply).
      #
      # @return [String] the compiled CSS
      def compiled_preflight
        require "tailwindcss/ruby"
        require "tmpdir"
        Dir.mktmpdir("poetry-preflight") do |dir|
          entry = File.join(dir, "entry.css")
          out = File.join(dir, "out.css")
          File.write(entry, %(@import "tailwindcss/theme.css" reference;\n@import "tailwindcss/preflight.css";\n))
          system(Tailwindcss::Ruby.executable, "-i", entry, "-o", out, exception: true, out: File::NULL, err: File::NULL)
          File.read(out)
        end
      end

      # The floor text: the header plus every preflight rule with its
      # top-level selectors wrapped in `:where()`.
      #
      # @param css [String] compiled preflight (defaults to a fresh compile)
      # @return [String]
      def floor(css = compiled_preflight)
        body = css.sub(%r{\A/\*!.*?\*/\s*}m, "")
        HEADER + wrap_rules(body)
      end

      # Wraps the selector list of every top-level style rule; at-rules and
      # nested content pass through untouched.
      #
      # @param css [String]
      # @return [String]
      def wrap_rules(css)
        out = +""
        depth = 0
        prelude_start = 0
        i = 0
        while i < css.length
          char = css[i]
          if char == "/" && css[i + 1] == "*"
            close = css.index("*/", i + 2) || (css.length - 2)
            i = close + 2
            next
          end
          case char
          when "{"
            if depth.zero?
              prelude = css[prelude_start...i]
              out << css[prelude_start...i].sub(prelude.strip, wrap_prelude(prelude.strip))
              out << "{"
              prelude_start = i + 1
            end
            depth += 1
          when "}"
            depth -= 1
            if depth.zero?
              out << css[prelude_start..i]
              prelude_start = i + 1
            end
          end
          i += 1
        end
        out << css[prelude_start..]
        out
      end

      # `:where()` around each selector of a list, except pseudo-element
      # selectors (`::placeholder`, `::-webkit-*`), which cannot be wrapped.
      #
      # @param prelude [String] a rule's selector list (or an at-rule prelude)
      # @return [String]
      def wrap_prelude(prelude)
        return prelude if prelude.start_with?("@")

        split_selectors(prelude).map do |selector|
          selector.include?("::") ? selector : ":where(#{selector})"
        end.join(", ")
      end

      # Splits a selector list on top-level commas (commas inside
      # parentheses and brackets belong to the selector).
      #
      # @param list [String]
      # @return [Array<String>]
      def split_selectors(list)
        selectors = []
        current = +""
        depth = 0
        list.each_char do |char|
          case char
          when "(", "[" then depth += 1
          when ")", "]" then depth -= 1
          end
          if char == "," && depth.zero?
            selectors << current.strip
            current = +""
          else
            current << char
          end
        end
        selectors << current.strip
        selectors.reject(&:empty?)
      end

      # The gem's committed floor.
      #
      # @return [Pathname]
      def path
        Poetry::Ui.root.join(RELATIVE_PATH)
      end

      # Writes the floor to its committed location.
      #
      # @return [Pathname] the written path
      def generate!
        path.dirname.mkpath
        path.write(floor)
        path
      end

      # False when the committed floor does not match a fresh generation.
      #
      # @return [Boolean]
      def verified?
        path.exist? && path.read == floor
      end

      # How a host's Tailwind entry stands on preflight: :preflight (the
      # full `@import "tailwindcss"`), :floor (poetry's reset floor imported),
      # or :none (neither - the case the installer and poetry:check warn about).
      #
      # @param entry [String] the entry stylesheet's text
      # @return [Symbol]
      def entry_state(entry)
        return :preflight if entry.match?(PREFLIGHT_IMPORT)
        return :floor if entry.match?(FLOOR_IMPORT)

        :none
      end
    end
  end
end
